name: docs

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: deploy-odoc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-odoc:
    name: Build odoc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Install dependencies
        run: |
          opam install . --deps-only --with-doc
          opam install odig

      - name: Build documentation
        run: |
          opam exec -- dune build @install --ignore-promoted-rules
          opam exec -- dune install --ignore-promoted-rules
          opam exec -- odig odoc bincaml --cache-dir _html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _html/html/bincaml

  deploy-odoc:
    name: Deploy odoc to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    needs: build-odoc

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      id-token: write
      pages: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
